### ISSUE TITLE
Installation of League of Legends: Command exited with code 256

### ISSUE THREAD

**Issue by blade1989** [flathub/net.lutris.Lutris#289] opened 2022-08-28 14:59 UTC
**Describe the problem**
During the `Installing League Of Legends` wizard, the stays for a long time on `Creating Wine Prefix`, and then exists with code 256.
See below for full error output, flatpak information.

**Is it reproducible with native Lutris?**

No. The native installation of Lutris does not have this bug. The LOL installer start fine.

**Steps to reproduce**

1. Klik the `+` Button
2. Select the `Search the Lutris website for installers`
3. Search for `League Of Legends`
4. Klik on `install` for the `Wine Standard` option.
5. Check the ` Create desktop shortcut` and `Create application menu shortcut`. Leave the installation dir to default(~/Games/league-of-legends). Klik on `Install`
6. Select the only available option for the L.O.L. installer, then press `Continue`.
7. Leave the preferred installation language to `English U.S.`. Then press continue.

If you have the 

**Expected behavior**
starting the League Of Legends Installer. Same as the native lutris installer.

**Actual behavior**
What actually happens. League Of Legends installer ends with: `Command exited with code 256`

See the full error output:
```bash
Gtk-Message: 16:06:29.868: Failed to load module "canberra-gtk-module"
2022-08-28 16:06:29,872: Starting Lutris 0.5.11
2022-08-28 16:06:30,005: Using NVIDIA drivers 515.65.01 for x86_64
2022-08-28 16:06:30,006: GPU: NVIDIA GeForce GTX 1050 Ti
2022-08-28 16:06:30,006: GPU: 10DE:1C82 1043:862A (nvidia drivers)
2022-08-28 16:06:30,342: Startup complete
2022-08-28 16:06:53,406: Download completed
2022-08-28 16:06:53,407: All files available
2022-08-28 16:06:53,407: All files are available, continuing install
/usr/lib/python3.9/site-packages/gi/overrides/GObject.py:493: Warning: ../gobject/gsignal.c:2731: instance '0x565352b6a500' has no handler with id '4333'
  return func(*args, **kwargs)
2022-08-28 16:06:54,745: Creating a win64 prefix in /home/REDACTED/Games/league-of-legends
2022-08-28 16:07:25,312: Wine prefix creation is taking longer than expected...
2022-08-28 16:15:15,437: No user.reg found after prefix creation. Prefix might not be valid
2022-08-28 16:15:15,459: Creating a win64 prefix in /home/REDACTED/Games/league-of-legends
2022-08-28 16:15:46,023: Wine prefix creation is taking longer than expected...
2022-08-28 16:23:36,145: No user.reg found after prefix creation. Prefix might not be valid
2022-08-28 16:23:36,178: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,480: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,480: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,480: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,665: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,665: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,666: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,666: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,848: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,848: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,848: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,848: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,982: Accessing game config while runner wasn't given one.
2022-08-28 16:23:36,983: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,341: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,341: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,342: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,342: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,342: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,435: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,435: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,435: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,435: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,435: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,517: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,517: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,517: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,517: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,517: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,617: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,617: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,617: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,617: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,618: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,724: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,724: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,724: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,724: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,725: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,761: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,761: Accessing game config while runner wasn't given one.
2022-08-28 16:23:37,761: The game doesn't have an executable
2022-08-28 16:23:37,761: Accessing game config while runner wasn't given one.
lutris-wrapper: /home/REDACTED/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-7.0-5-x86_64/bin/wine
Started initial process 79 from /home/REDACTED/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-7.0-5-x86_64/bin/wine /home/REDACTED/Games/league-of-legends/drive_c/windows/explorer.exe /home/REDACTED/.var/app/net.lutris.Lutris/cache/lutris/installer/league-of-legends/lol_installer/live.na.exe
Start monitoring process.
modify_ldt: Operation not permitted
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2022-08-28 16:23:38,771: Command exited with code 256
None
2022-08-28 16:23:49,484: Cancelling installation of League of Legends
2022-08-28 16:23:55,573: Shutting down Lutris
```

**Flatpak info**

 - Flatpak: `1.12.7`
 - `flatpak --gl-drivers`:

```bash
nvidia-515-65-01
default
host
```

 - `flatpak info net.lutris.Lutris` :

```bash
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 917,8 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: 46f4d8bdde456e6f056b02cb78221837ddbee9f6db8a8b1efe6842299d424ca0
      Parent: a01b319ac3c027b79ddd2240a9eeb5f74862f00bf3a2476bcc75550a93d9fae2
     Subject: Remove references to Flathub Beta (8466669b)
        Date: 2022-08-27 01:30:43 +0000
```

 - `flatpak permission-show net.lutris.Lutris`:

```bash
Table         Object       App               Permissions                  Data
notifications notification net.lutris.Lutris yes                          0x00
documents     c4d96ba1     net.lutris.Lutris read,write,grant-permissions (b'/usr/games/0ad', 64769, 46006275, 0)
documents     dcd76207     net.lutris.Lutris read,grant-permissions       (b'/usr/games', 64769, 46006275, 4)
background    background   net.lutris.Lutris yes                          0x00

**Comment by strycore** [comment] 2022-08-28 22:39
Duplicate of #85

**Closed by strycore** 2022-08-28 22:39 UTC
