### ISSUE TITLE
Lutris stops running when org.freedesktop.Platform.GL.default for Flathub is installed

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#54] opened 2019-09-19 07:23 UTC
When org.freedesktop.Platform.GL.default is installed from flathub, Lutris stops running and it yields the following error messages:
```
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```
Removing org.freedesktop.Platform.GL.default makes Lutris work again.

**Comment by gasinvein** [comment] 2019-09-19 09:47
Is `org.gnome.Platform.Compat.i386//3.34` installed?

**Comment by Saroufim** [comment] 2019-09-19 10:42
That was the issue. Thank you very much. Is this a flatpak bug perhaps for not pulling the right dependencies?

**Comment by gasinvein** [comment] 2019-09-19 10:55
Likely so. This is seems to be a duplicate of #53.

**Closed by gasinvein** 2019-09-19 10:55 UTC
