### ISSUE TITLE
Garena don't install in Fedora Kinoite

### ISSUE THREAD

**Issue by zihadio** [flathub/net.lutris.Lutris#285] opened 2022-08-26 05:48 UTC
**Describe the problem**
It seems I can't install Garena launcher from lutris.

**Is it reproducible with native Lutris?**
No.

**Steps to reproduce**
1. Install lutris from flathub

**Expected behavior**
Garena should be installed.

**Actual behavior**
Garena install is stuck in "Creating wine prefix".

**Flatpak info**
`Flatpak 1.12.7`
`flatpak --gl-drivers  
default  
host`  

here's the log

```
[zihad@fedora ~]$ flatpak run net.lutris.Lutris
2022-08-26 11:41:36,199: Starting Lutris 0.5.11
2022-08-26 11:41:36,374: Running Intel Mesa driver 21.3.9 on Mesa Intel(R) HD Graphics 4600 (HSW GT2) (0x416)
2022-08-26 11:41:36,375: GPU: 8086:0416 1043:178D (i915 drivers)
2022-08-26 11:41:36,375: GPU: 10DE:1391 1043:178D (nouveau drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
2022-08-26 11:41:36,967: Startup complete
2022-08-26 11:43:49,839: Download completed
2022-08-26 11:43:49,840: All files available
2022-08-26 11:43:49,840: All files are available, continuing install
2022-08-26 11:43:49,847: Creating a win64 prefix in /home/zihad/Games/garena
2022-08-26 11:44:20,435: Wine prefix creation is taking longer than expected...
```

**Comment by strycore** [comment] 2022-08-26 17:33
Duplicate of https://github.com/flathub/net.lutris.Lutris/issues/85

**Closed by strycore** 2022-08-26 17:33 UTC
