### ISSUE TITLE
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system Error

### ISSUE THREAD

**Issue by hovo1990** [flathub/net.lutris.Lutris#61] opened 2019-10-11 17:27 UTC
Hello,

When trying to launch lutris, I get the following error:
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256

Is there anything that can be done?
Best regards,
Hovakim

**Comment by rowbawts** [comment] 2019-10-11 17:36
> Try
> 
> ```
> $ flatpak install org.gnome.Platform.Compat.i386
> ```
> 
> Then choose 3.34 if it gives you a choice.

This worked for me flatpak uninstall --unused removes it due to a bug in flatpak so don't run that command until they fix it or you will encounter this issue again.

**Comment by gasinvein** [comment] 2019-10-11 18:38
Duplicate of #53

**Closed by gasinvein** 2019-10-11 18:38 UTC

**Comment by hovo1990** [comment] 2019-10-11 19:02
Thanks it solved the problem )
